### ISSUE TITLE
BIOS question

### ISSUE THREAD

**Issue by dstroe2000** [gemini64/opencore-msi-x99a#1]
"Make sure you are running the latest BIOS, you can find the latest update file here."
It is BIOS 7885v1E or 7885v1F2(Beta version)? 
Thanks!

**Comment by gemini64** [comment]
7885v1F2(Beta version), as written in the readme.
This is just to set a common reference point; the bios version 7885v1F2 has been tested by me and seems to works fine.

**Comment by dstroe2000** [comment]
Thanks for the note!
